/**
 * @license
 *
 * Hyphenation patterns for Tamil (ta)
 *
 * URL: http://www.hyphenation.org/tex
 * Source: hyph-utf8 project
 *
 * Copyright (C) 2016 Santhosh Thottingal
 *
 * name: MIT url: https://opensource.org/licenses/MIT text: > Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. name: LGPL version: 3 or_later: true url: http://www.gnu.org/licenses/lgpl.html name: GPL version: 3 or_later: true url: http://www.gnu.org/licenses/gpl.html
 *
 */

// Avoid circular dependencies
type HyphenationTrieNode = import('./index').HyphenationTrieNode;

export const ta_patterns: HyphenationTrieNode = {"patterns":null,"children":{"‍":{"patterns":[2,2],"children":{}},"‌":{"patterns":[1,1],"children":{}},"அ":{"patterns":[1,1],"children":{}},"ஆ":{"patterns":[1,1],"children":{}},"இ":{"patterns":[1,1],"children":{}},"ஈ":{"patterns":[1,1],"children":{}},"உ":{"patterns":[1,1],"children":{}},"ஊ":{"patterns":[1,1],"children":{}},"எ":{"patterns":[1,1],"children":{}},"ஏ":{"patterns":[1,1],"children":{}},"ஐ":{"patterns":[1,1],"children":{}},"ஒ":{"patterns":[1,1],"children":{}},"ஓ":{"patterns":[1,1],"children":{}},"ஔ":{"patterns":[1,1],"children":{}},"ா":{"patterns":[0,1],"children":{}},"ி":{"patterns":[0,1],"children":{}},"ீ":{"patterns":[0,1],"children":{}},"ு":{"patterns":[0,1],"children":{}},"ூ":{"patterns":[0,1],"children":{}},"ெ":{"patterns":[0,1],"children":{}},"ே":{"patterns":[0,1],"children":{}},"ை":{"patterns":[0,1],"children":{}},"ொ":{"patterns":[0,1],"children":{}},"ோ":{"patterns":[0,1],"children":{}},"ௌ":{"patterns":[0,1],"children":{}},"க":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ங":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ச":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ஜ":{"patterns":[1,0],"children":{}},"ஞ":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ட":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ண":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"த":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ந":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ப":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ம":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ய":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ர":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ற":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ல":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ள":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ழ":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"வ":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ஷ":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ஸ":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ஹ":{"patterns":[1,0],"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ன":{"patterns":null,"children":{"்":{"patterns":[2,0,1],"children":{}}}},"ஂ":{"patterns":[2,1],"children":{}},"ஃ":{"patterns":[2,1],"children":{}},"ௗ":{"patterns":[2,1],"children":{}},"்":{"patterns":[2,1],"children":{}}}};

export default ta_patterns;
